/**
 * PAIN POINT TAB
 * 
 * Displays:
 * - Dual-line chart: val_loss & val_accuracy across epochs (if training_log loaded)
 * - Error-rate-by-premise-length-bucket chart (if val_predictions loaded)
 * - Oxblood highlighting on worst data points
 * - Clear empty states when optional data is not available
 *
 * INSIGHT: The length-bucket analysis reveals whether the model struggles more
 * with shorter (ambiguous) or longer (complex) premises. Bucketing in SQL with
 * CASE expressions is far more efficient than post-hoc JS binning because DuckDB
 * computes the aggregation in a single scan without materializing per-row objects.
 */

import { useMemo } from 'react';
import {
  LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid,
  BarChart, Bar, Cell, ReferenceDot, Legend,
} from 'recharts';
import { useQuery } from '../hooks/useQuery';
import { useAppContext } from '../context/AppContext';

// ─── Types ────────────────────────────────────────────────────────────────────

type EpochRow = {
  epoch: number;
  train_loss: number;
  val_loss: number;
  val_accuracy: number;
};

type BucketRow = {
  bucket: string;
  error_rate: number;
  total: number;
};

export function PainPointTab() {
  const { languageFilter, availability } = useAppContext();

  // ─── Training Curves ────────────────────────────────────────────────────────
  const epochSql = useMemo(() => {
    if (!availability.trainingLog) return null;
    return `SELECT epoch, train_loss, val_loss, val_accuracy FROM training_log ORDER BY epoch;`;
  }, [availability.trainingLog]);

  const { data: epochData } = useQuery<EpochRow>(epochSql);

  // Find worst points for oxblood highlighting
  const worstLoss = useMemo(() => {
    if (!epochData.length) return null;
    return epochData.reduce((max, row) => row.val_loss > max.val_loss ? row : max, epochData[0]);
  }, [epochData]);

  const worstAcc = useMemo(() => {
    if (!epochData.length) return null;
    return epochData.reduce((min, row) => row.val_accuracy < min.val_accuracy ? row : min, epochData[0]);
  }, [epochData]);

  // ─── Error Rate by Length Bucket ────────────────────────────────────────────
  const bucketSql = useMemo(() => {
    if (!availability.valPredictions) return null;
    const langJoin = languageFilter
      ? `AND v.language = '${languageFilter}'`
      : '';
    return `
      WITH joined AS (
        SELECT
          t.premise_word_count,
          CASE WHEN v.true_label != v.predicted_label THEN 1 ELSE 0 END AS is_error
        FROM val_predictions v
        JOIN train t ON v.id = t.id
        WHERE 1=1 ${langJoin}
      )
      SELECT
        CASE
          WHEN premise_word_count <= 10 THEN '0-10'
          WHEN premise_word_count <= 20 THEN '11-20'
          WHEN premise_word_count <= 30 THEN '21-30'
          WHEN premise_word_count <= 40 THEN '31-40'
          ELSE '40+'
        END AS bucket,
        ROUND(100.0 * SUM(is_error) / COUNT(*), 1) AS error_rate,
        COUNT(*) AS total
      FROM joined
      GROUP BY bucket
      ORDER BY bucket;
    `;
  }, [availability.valPredictions, languageFilter]);

  const { data: bucketData } = useQuery<BucketRow>(bucketSql, [languageFilter]);

  // Find worst bucket for oxblood
  const worstBucket = useMemo(() => {
    if (!bucketData.length) return null;
    return bucketData.reduce((max, row) => row.error_rate > max.error_rate ? row : max, bucketData[0]);
  }, [bucketData]);

  // ─── Render ─────────────────────────────────────────────────────────────────

  const hasAnyData = availability.trainingLog || availability.valPredictions;

  if (!hasAnyData) {
    return (
      <div className="empty-state">
        <h3>No Training Metrics Available Yet</h3>
        <p>
          This tab will show validation loss/accuracy curves and error analysis
          once <code>training_log_cleaned.parquet</code> and/or{' '}
          <code>val_predictions_cleaned.parquet</code> are generated by the pipeline.
        </p>
      </div>
    );
  }

  return (
    <div>
      {/* Training Curves */}
      {availability.trainingLog && epochData.length > 0 && (
        <div className="card">
          <h2>Training Curves — Loss &amp; Accuracy per Epoch</h2>
          <div className="chart-container">
            <ResponsiveContainer width="100%" height={300}>
              <LineChart data={epochData} margin={{ top: 10, right: 30, bottom: 20, left: 40 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#E0D8CC" />
                <XAxis dataKey="epoch" tick={{ fontSize: 11 }} label={{ value: 'Epoch', position: 'bottom', fontSize: 12 }} />
                <YAxis yAxisId="loss" tick={{ fontSize: 11 }} label={{ value: 'Loss', angle: -90, position: 'insideLeft', fontSize: 12 }} />
                <YAxis yAxisId="acc" orientation="right" tick={{ fontSize: 11 }} label={{ value: 'Accuracy', angle: 90, position: 'insideRight', fontSize: 12 }} />
                <Tooltip contentStyle={{ background: '#fff', border: '1px solid #E0D8CC', borderRadius: '6px', fontSize: '0.8125rem' }} />
                <Legend />
                <Line yAxisId="loss" type="monotone" dataKey="train_loss" stroke="#2D5016" strokeWidth={2} name="Train Loss" dot={false} />
                <Line yAxisId="loss" type="monotone" dataKey="val_loss" stroke="#4A7C28" strokeWidth={2} name="Val Loss" dot={false} />
                <Line yAxisId="acc" type="monotone" dataKey="val_accuracy" stroke="#6B6B6B" strokeWidth={2} strokeDasharray="4 2" name="Val Accuracy" dot={false} />
                {worstLoss && (
                  <ReferenceDot yAxisId="loss" x={worstLoss.epoch} y={worstLoss.val_loss} r={6} fill="#722F37" stroke="#722F37" />
                )}
                {worstAcc && (
                  <ReferenceDot yAxisId="acc" x={worstAcc.epoch} y={worstAcc.val_accuracy} r={6} fill="#722F37" stroke="#722F37" />
                )}
              </LineChart>
            </ResponsiveContainer>
          </div>
          {worstLoss && (
            <div className="insight-callout error">
              Worst validation loss: <strong>{worstLoss.val_loss.toFixed(4)}</strong> at epoch {worstLoss.epoch}.
              {worstAcc && ` Lowest accuracy: ${(worstAcc.val_accuracy * 100).toFixed(1)}% at epoch ${worstAcc.epoch}.`}
            </div>
          )}
        </div>
      )}

      {/* Error Rate by Premise Length Bucket */}
      {availability.valPredictions && bucketData.length > 0 && (
        <div className="card">
          <h2>Error Rate by Premise Length (word count buckets)</h2>
          <div className="chart-container">
            <ResponsiveContainer width="100%" height={280}>
              <BarChart data={bucketData} margin={{ top: 10, right: 20, bottom: 20, left: 40 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#E0D8CC" />
                <XAxis dataKey="bucket" tick={{ fontSize: 11 }} label={{ value: 'Words in Premise', position: 'bottom', fontSize: 12 }} />
                <YAxis tick={{ fontSize: 11 }} label={{ value: 'Error Rate %', angle: -90, position: 'insideLeft', fontSize: 12 }} />
                <Tooltip
                  contentStyle={{ background: '#fff', border: '1px solid #E0D8CC', borderRadius: '6px', fontSize: '0.8125rem' }}
                  formatter={(value) => [`${value}%`, 'Error Rate']}
                />
                <Bar dataKey="error_rate" radius={[3, 3, 0, 0]} name="Error Rate %">
                  {bucketData.map((entry) => (
                    <Cell
                      key={entry.bucket}
                      fill={entry.bucket === worstBucket?.bucket ? '#722F37' : '#2D5016'}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
          {worstBucket && (
            <div className="insight-callout error">
              Highest error rate: <strong>{worstBucket.error_rate}%</strong> for premises
              with {worstBucket.bucket} words ({worstBucket.total} samples).
            </div>
          )}
        </div>
      )}

      {/* Partial empty states */}
      {!availability.trainingLog && (
        <div className="card">
          <div className="empty-state">
            <h3>Training Curves Not Available</h3>
            <p>Add <code>training_log_cleaned.parquet</code> to see loss/accuracy trends.</p>
          </div>
        </div>
      )}
      {!availability.valPredictions && (
        <div className="card">
          <div className="empty-state">
            <h3>Error Analysis Not Available</h3>
            <p>Add <code>val_predictions_cleaned.parquet</code> to see error-rate-by-length analysis.</p>
          </div>
        </div>
      )}
    </div>
  );
}
